### PR TITLE
Added custom css and js.

### PR DESCRIPTION
**Pull request by targodan**
I have added the posibility to add custom css and js files because I needed it.

As I think this might be helpful for more people than just me I created this pull request. ;)

### CODE REVIEW

**Comment by yoshiharuyamashita** [comment]
Hi @targodan 

Wouldn't it be easier to override "layouts/partials/head.html" instead? Also how would this work if you wanted to include multiple css and/or js files?

**Comment by targodan** [comment]
Hi @yoshiharuyamashita

> Wouldn't it be easier to override "layouts/partials/head.html" instead?

My idea was to use the insertion of css and js files just as a tweak or an extension. Not in order to make big changes to the look and feel.

If I were to override "layouts/partials/head.html" I would either have to copy paste your file or write my own. As any programmer I am lazy and don't want to do either of those. :wink:

> Also how would this work if you wanted to include multiple css and/or js files?

Including multiple files is no problem as the parameter is an array. Just take a look at my commit e6f9b6554ffc77de29faf72f1c5c66a2bc29047f

**Comment by targodan** [comment]
One practical example would be adding [EmojiOne](http://emojione.com/) to a blog. Just as I did with [mine](https://www.targodan.de/post/about/).

All I had to do was download the EmojiOne js and css and write about 4 lines of code and config:

```
  custom_css = ["css/emojione.min.css"]
  custom_js = ["js/jquery.min.js", "js/emojione.min.js", "js/enableEmojione.js"]
```

And the js script in case anyone is interested:

```javascript
$(document).ready(function() {
    $('p,li').each(function() {
        this.innerHTML = emojione.shortnameToImage(this.innerHTML);
    });
});
```

The theme of the site is currently running of my fork.

**Comment by yoshiharuyamashita** [comment]
Thank you for clarifying @targodan. I now see how useful this is and I like it! Cheers!

**Pull request merged**
