### PR TITLE
add Weibo support for side menu

### PR DESCRIPTION
**Pull request by xusiwei**

### CODE REVIEW

**Comment by yoshiharuyamashita** [comment]
@xusiwei

I was planning to add support for more social network sites. I'll add Weibo as part of that.

Cheers!

**Comment by xusiwei** [comment]
@yoshiharuyamashita 
yeap, I only want to push one commit to your repo, but sorry, it seems like something wrong in my ops.

**Comment by xusiwei** [comment]
as [the guide](https://help.github.com/articles/using-pull-requests/) say, 
> After you send a pull request, **any commit that's pushed to your branch will be automatically added to your pull request**, which is useful if you're making additional changes.

**Comment by yoshiharuyamashita** [comment]
I see. Thanks for the info.

**Comment by yoshiharuyamashita** [comment]
I've now added Weibo among with other SNS sites.

**Pull request closed without merging**
